In [35]:
for x in range(1,100)
 count = 0
    for i in range(2,(x//2+1)):
        if (x%i==0):
            count=count+1
            break
    if (count==0 and x !=1):
        print("%d" %x, end=' ')

SyntaxError: expected ':' (2376781909.py, line 1)

In [55]:
for i in range(0,100):
    flag=True
    for j in range(2,i):
        if (i%j == 0):
            flag=False
            break
    if (flag == True):
            print(i)

0
1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [71]:
def prime_number(n):
    primes=[]
    for i in range (2,n+1):
        for j in range(2,int(i**0.5)+1):
            if i%j == 0:
                break
        else:
            primes.append(i)
    return primes

In [72]:
prime_list= prime_number(100)
print(prime_list)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [79]:
import numpy as np
array1 = np.array([5,6,7])
array1


array([5, 6, 7])

In [75]:
array1 = np.zeros((4,5))

In [76]:
array1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
array2 = np.arange(0,10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x = list(("sam", "rat", "emon"))
print(x)
print(type(x)) 

['sam', 'rat', 'emon']
<class 'list'>


In [81]:
x = tuple(("sam", "rat", "emon"))
print(x)
print(type(x)) 

('sam', 'rat', 'emon')
<class 'tuple'>


In [82]:
x = dict(name="Samrat", age=24)
print(x)
print(type(x)) 

{'name': 'Samrat', 'age': 24}
<class 'dict'>


In [83]:
x = set(("Sam", "rat", "Emon"))
print(x)
print(type(x)) 

{'rat', 'Sam', 'Emon'}
<class 'set'>
