In [1]:
!pip install ga


Defaulting to user installation because normal site-packages is not writeable


In [2]:
# Cell 1: Install the 'ga' package if not already installed
!pip install ga


Defaulting to user installation because normal site-packages is not writeable


In [6]:
from ga.algorithms import GeneticAlgorithm


ImportError: cannot import name 'GeneticAlgorithm' from 'ga.algorithms' (C:\Users\MONIRUL ISLAM\AppData\Roaming\Python\Python311\site-packages\ga\algorithms.py)

In [7]:
import ga
help(ga)
help(ga.algorithms)


Help on package ga:

NAME
    ga

PACKAGE CONTENTS
    algorithms
    chromosomes
    examples (package)
    genes
    translators
    util

DATA
    __all__ = ['genes', 'chromosomes', 'translators', 'algorithms', 'util'...

FILE
    c:\users\monirul islam\appdata\roaming\python\python311\site-packages\ga\__init__.py


Help on module ga.algorithms in ga:

NAME
    ga.algorithms

CLASSES
    abc.ABC(builtins.object)
        BaseGeneticAlgorithm
    
    class BaseGeneticAlgorithm(abc.ABC)
     |  BaseGeneticAlgorithm(chromosomes, translator=None, abs_fit_weight=0.25, rel_fit_weight=0.75)
     |  
     |  Base genetic algorithm.
     |  
     |  Subclasses must override the ``eval_fitness`` method.
     |  
     |  Method resolution order:
     |      BaseGeneticAlgorithm
     |      abc.ABC
     |      builtins.object
     |  
     |  Methods defined here:
     |  
     |  __init__(self, chromosomes, translator=None, abs_fit_weight=0.25, rel_fit_weight=0.75)
     |      Construct a new 

In [11]:
import numpy as np
# Implementing the GA
#Calcuate fitness of population

def calculate_fitness(inputs, population):
    

    fitness = np.sum(population*inputs, axis=1)
    

# Specify inputs of the equation ( X values)
inputs = [4,-2,3.5,-4.2]

# Specify the number of weights or multipliers (A values, in our case) for each input which we are looking to optimize
number_of_weights = 4

# Specify the number of solutions in each generation. Each solution will have the number of weights
solutions = 6

#Specify the number of parents mating to yield the specified number of solutions
number_of_parents_mating = 3

# Define the population size based on the number of parents mating and the number of solutions
population_size = (solutions,number_of_weights)

#randomly create the inital population according to the specified population size
new_population = np.random.uniform(low=-5.0, high=5.0, size=population_size)

#Print out the initialized population
print(new_population)


#Specify the number of generations to mutate through 
number_of_generations = 10

#Loop over the specified number of generations

for generation in range(number_of_generations):
    
    #Print the generation in which we are currently looping through to keep track
    print("Generation : ", generation)
    
    # Calculate the fitness of the population in the current generation
    fitness = calculate_fitness(inputs, new_population)

    # Proceed to select the most fit parents to mate
    parents = choose_mating(new_population, fitness, 
                                      number_of_parents_mating)

    # Proceed to create offsprings via the one point cross over
    crossover = crossingover(parents,
                                       size_of_offspring=(population_size[0]-parents.shape[0], number_of_weights))

    # Proceed to add random bias to the genes of the created offspring via the mutation function
    mutated = mutation(crossover)

    # Proceed to create the new population from the parents and the mutated
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = mutated

    # Get the best or most fit solution in this current generation
    print("Best result : ", np.max(np.sum(new_population*inputs, axis=1)))

[[ 1.52378311 -3.82800395 -1.92792133 -0.44221676]
 [-3.0207095  -4.32456131 -0.88338974 -3.83983941]
 [ 3.36676936  1.1639582  -1.91554405 -3.85104764]
 [-4.8112275   3.34371238 -4.17448204  4.90032559]
 [-4.64462865 -4.26206621  0.07152676 -0.42237179]
 [-0.58781403  0.34988755 -0.08645706 -4.47346188]]
Generation :  0


NameError: name 'choose_mating' is not defined